# Generated by Django 6.0.3 on 2026-04-03 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='nom categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100, unique=True, verbose_name="Titre de l'article")),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='numero slug')),
                ('contenu', models.CharField(max_length=50, verbose_name='contenu articles')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles_images', verbose_name='image')),
                ('statut', models.IntegerField(choices=[(0, 'Brouillon'), (1, 'Publier')], default=0, verbose_name='status article')),
                ('date_creation', models.DateField(verbose_name='date creation')),
                ('date_publication', models.DateField(auto_now_add=True, verbose_name='date publication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateurs')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.categorie', verbose_name='categorie article')),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='message commentaire')),
                ('date_publication', models.DateField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
