# Generated by Django 6.0.3 on 2026-04-05 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_article_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
        migrations.AlterField(
            model_name='article',
            name='date_creation',
            field=models.DateField(auto_now_add=True, verbose_name='date creation'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_publication',
            field=models.DateField(auto_now=True, verbose_name='date publication'),
        ),
    ]
