# Generated by Django 6.0.3 on 2026-04-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_article_slug_alter_article_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date creation'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_publication',
            field=models.DateTimeField(auto_now=True, verbose_name='date publication'),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='date_publication',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
